name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*' # Triggers whenever you push a tag like v3.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip the extension files
        run: |
          zip -r SCB-Elite-${{ github.ref_name }}.zip . -x ".git/*" ".github/*" ".gitignore" "README.md"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: SCB-Elite-${{ github.ref_name }}.zip
          name: SCB Elite ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload and Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload-action@v1.1.1
        with:
          file-path: SCB-Elite-${{ github.ref_name }}.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true
